---
title: "Studiewijzer"
---

# Inhoud

Deze module wil een inleiding geven tot de gangbare klassieke bivariate en multivariate technieken van statistische analyse binnen het onderwijskundig onderzoek. De module is vooral op de praktijk afgestemd. Dit impliceert dat er geen aandacht wordt besteed aan streng wiskundige bewijzen, maar zoveel mogelijk praktische problemen worden behandeld. 

Eerst staan we stil bij hoe we een kwantitatieve onderzoeksvraag kunnen vertalen in een formeel analysemodel. Op basis van dit analysemodel kunnen we dan de meest gepaste analysetechniek selecteren. Daarna leren we verschillende bivariate en multivariate analysetechnieken uitvoeren in RStudio om analysemodellen te testen, schatten en interpreteren. 

# Doelstellingen

Wat wordt je verwacht te kunnen na het volgen van dit opleidingsonderdeel?

Algemeen: 

Je bent in staat om zelf eenvoudige onderzoeksvragen over niet-causale en causale verbanden tussen één of meerdere kenmerken, statistisch te onderzoeken. Ook kan je wetenschappelijke publicaties waarin gebruik gemaakt wordt van kruistabellen, correlaties, t-testen, ANOVA en regressieanalyse (al dan niet met dummy-variabelen en interacties) begrijpen en interpreteren. 

 

Meer specifiek:  

Je kan een bivariate of multivariate kwantitatieve analyse uitvoeren. 

Hiertoe onderscheiden we de volgende deelvaardigheden: 

\- je kan de juiste techniek associëren bij een bepaald analysemodel; 

\- je kan een t-test uitvoeren, interpreteren en rapporteren; 

\- je kan een onderzoek a.d.h.v. kruistabellen uitvoeren, interpreteren en rapporteren; 

\- je kan een correlatieonderzoek uitvoeren, interpreteren en rapporteren; 

\- je kan een ANOVA uitvoeren, interpreteren en rapporteren; 

\- je kan een bivariate en meervoudige regressieanalyse uitvoeren, interpreteren en rapporteren; 

\- je kan regressieanalyse met dummy-variabelen en interactievariabelen uitvoeren, interpreteren en rapporteren; 

\- je kan voor elk van deze technieken de assumpties nagaan. 

# Leermateriaal

Het boek ‘Bivariate en multivariate statistiek met R. Een openleerpakket.’ De Maeyer, Coertjens en Ardies (2012) vormt het studiemateriaal voor dit opleidingsonderdeel. Dit boek is verkrijgbaar bij Acco. We raden je aan om telkens voor de les het hoofdstuk (of de hoofdstukken) voor die les door te nemen. 

Naast dit verplichte cursusmateriaal zijn er ook zelfstudieopdrachten (ZSO’s) op het Studentenportaal terug te vinden. Deze ZSO’s zijn telkens oefeningen waarin de aangereikte leerstof moet worden toegepast op reële datasets. Ook de respons op deze oefeningen is beschikbaar op het Studentenportaal. 

Voor dit opleidingsonderdeel maken we gebruik van de softwarepakketten R en RStudio. Deze zijn gratis te downloaden van www.r-project.org en www.posit.co en kunnen op de courante besturingssystemen geïnstalleerd worden. Studenten die nog niet vertrouwd zijn met het werken met R kunnen best eerst het boek ‘Univariate statistiek voor de menswetenschappen. Een openleerpakket in R’ van De Maeyer, van Daal en Vandervieren doornemen. Dit boek is o.a. verkrijgbaar bij Acco. 

# Schematisch overzicht

Voor dit vak zijn 8 contactmomenten voorzien. Om meerwaarde te halen uit de contactmomenten dien je op voorhand de relevante hoofdstukken uit het OLP door te nemen en de bijhorende videolessen te bekijken.  

# Evaluatie

De evaluatie van statistiek B bestaat uit een schriftelijk PC-examen dat in twee delen is opgesplitst: 

-   een gesloten boek gedeelte waarin naar kennis en inzicht gepeild wordt (70% van de punten); 

<!-- -->

-   een open boek gedeelte dat focust op je vermogen om analyses uit te voeren in RStudio (30% van de punten).  

Je moet minimaal de helft halen op het gesloten deel om te kunnen slagen voor Statistiek B. Anders bedraagt de score voor Statistiek B maximaal 8/20.  

# Onderwijsteam

Het onderwijsteam voor dit opleidingsonderdeel bestaat uit Sven De Maeyer en Sofie Vermeiren. Heb je vragen over “Statistiek B” praktisch of inhoudelijk van aard? Dan stel je deze steeds eerst via het discussieforum op de het Studentenportaal. Dit zal wekelijks worden nagekeken en opgevolgd.  

[Sven.Demaeyer\@uantwerpen.be](mailto:Sven.Demaeyer@uantwerpen.be) 

[Sofie.Vermeiren\@uantwerpen.be](mailto:Sofie.Vermeiren@uantwerpen.be) 
