<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="be-nl" xml:lang="be-nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Contactmoment 6: Respons computer lab – Statistiek B</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f37e791e91ce963a691f9e91e98c8721.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WB6XE1H6V1"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WB6XE1H6V1', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"be-nl"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <div id="quarto-announcement" data-announcement-id="b0e362a38869e05bc3e01903c80d0932" class="alert alert-primary hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><strong>Alert</strong> - deze website is nog in ontwikkeling - feedback altijd welkom via sven.demaeyer@uantwperen.be</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Contactmoment 6: Respons computer lab</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/STAT B.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../images/STAT B.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://www.uantwerpen.be/nl/" title="uantwerpen.be/nl/" class="quarto-navigation-tool px-1" aria-label="uantwerpen.be/nl/"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/Sdemaeyer2/STATB_2425" title="Statistiek B" class="quarto-navigation-tool px-1" aria-label="Statistiek B"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welkom</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../OLP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Open Leer Pakket</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Contactmomenten/Contactmomenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contactmomenten</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C1/C1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C2/C2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C3/C3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C4/C4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C5/C5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C6/C6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Contactmomenten/C7/C7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">C7</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Penguins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Online (R) oefeningen</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_t_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_kruistabellen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_correlaties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Zelftest_bivariate_regressie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bivariate regressie</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../computer_labs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computer labs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">ZSO</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO1: van vraag naar methode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO2: t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO3: ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO4: Kruistabellen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO5: Correlaties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO6: Bivariate regressie</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO7: Multivariate regressie en assumpties</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ZSO/ZSO8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ZSO8: Dummy-variabelen en interacties</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Rapporteren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rapporteren</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../t_test_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">t-test rapporteren</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ANOVA_Rapportage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA rapporteren</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../Scrollytelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepten in beeld</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/OLS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OLS uitgelegd</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/R_kwadraat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R-kwadraat uitgelegd</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/CI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Betrouwbaarheidsintervallen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/T_toets_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De t-toets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/NormaalVerdeling_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">De normaalverdeling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Scrollytelling_pages/CentraleLimietstelling_test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Centrale limietstelling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Screencasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Screencasts</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Extra materiaal</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Extra/Projecten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Projecten in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Extra/Quarto_documenten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto documenten</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Extra/dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">dplyr en tidyr</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../studiewijzer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Studiewijzer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#oefening-1" id="toc-oefening-1" class="nav-link active" data-scroll-target="#oefening-1">Oefening 1</a></li>
  <li><a href="#oefening-2" id="toc-oefening-2" class="nav-link" data-scroll-target="#oefening-2">Oefening 2</a></li>
  <li><a href="#oefening-3" id="toc-oefening-3" class="nav-link" data-scroll-target="#oefening-3">Oefening 3</a></li>
  <li><a href="#oefening-4" id="toc-oefening-4" class="nav-link" data-scroll-target="#oefening-4">Oefening 4</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Respons_C6.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Contactmoment 6: Respons computer lab</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vooraleer je de oefeningen kan oplossen is het belangrijk om zowel de dataset te laden, het pakket <code>car</code> te activeren en ook de OLP2 Functies te activeren.</p>
</div>
</div>
<section id="oefening-1" class="level2">
<h2 class="anchored" data-anchor-id="oefening-1">Oefening 1</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><i class="bi bi-journal-richtext"></i> Oefening 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Is er een verschil tussen eerste en tweedejaars in technische geletterdheid (<code>TAC.na</code>) en is het zo dat het effect van “eigen inbreng in de les” (<code>PISA_EigenInbreng</code>) op de technische geletterdheid anders is voor eerste dan wel voor tweedejaars (<code>Studiejaar</code>)?</p>
<p>Vooraleer je deze analyse draait, maak je een dummyvariabele aan voor de variabele <code>Studiejaar</code>. Zorg ervoor dat deze dummy aanstaat voor de categorie “tweedejaars”. Hanteer deze dummyvariabele in je verdere analyses.</p>
</div>
</div>
<p>We starten met het aanmaken van de dummy variabele en checken of we dit goed gedaan hebben door een tabel aan te maken waarin we de oorspronkelijke variabele kruisen met de aangemaakte dummy variabele.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Tweedejaars<span class="ot">&lt;-</span>(Techniek<span class="sc">$</span>Studiejaar<span class="sc">==</span><span class="st">'2'</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Techniek<span class="sc">$</span>Studiejaar,Techniek<span class="sc">$</span>Tweedejaars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       0    1
  1 1083    0
  2    0 1284</code></pre>
</div>
</div>
<p>We schatten nu het model met daarin enerzijds de hoofdeffecten van <code>PISA_EigenInbreng</code> en <code>Tweedejaars</code> en anderzijds het interactie-effect tussen beide. (Je merkt in onderstaand codeblok dat we werken met wat meer ‘enters’ en de code over lijnen spreiden om ze leesbaar te houden)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>M_EigenInbreng <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  TAC.na <span class="sc">~</span> PISA_EigenInbreng <span class="sc">+</span> Tweedejaars <span class="sc">+</span> PISA_EigenInbreng<span class="sc">*</span>Tweedejaars,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>Techniek</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_EigenInbreng)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TAC.na ~ PISA_EigenInbreng + Tweedejaars + PISA_EigenInbreng * 
    Tweedejaars, data = Techniek)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.62846 -0.14602  0.01189  0.16344  0.47802 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    0.679370   0.018249  37.228  &lt; 2e-16 ***
PISA_EigenInbreng             -0.053860   0.009498  -5.671 1.67e-08 ***
Tweedejaars                    0.010221   0.024576   0.416    0.678    
PISA_EigenInbreng:Tweedejaars -0.007273   0.013114  -0.555    0.579    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2041 on 1675 degrees of freedom
  (688 observations deleted due to missingness)
Multiple R-squared:  0.04447,   Adjusted R-squared:  0.04275 
F-statistic: 25.98 on 3 and 1675 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>De mate waarin leerlingen eigen inbreng mogen doen, het studiejaar waarin leerlingen zitten en de interactie tussen deze beide variabelen verklaren samen 4.28% van de variantie (R-kwadraat = 0.0428) in technische geletterdheid (<code>TAC.na</code>). We verwachten dat deze variabelen ook in de populatie een invloed gaan hebben op technische geletterdheid (F(3,1675) = 25.98, p &lt; 0.001).</p>
<p>Aangaande de vraag of er een verschil is in technische geletterdheid tussen eerste- en tweedejaars studenten stellen we vast dat er geen statistisch significant effect is van de variabele <code>Tweedejaars</code> op <code>TAC.na</code> (β = 0.01, p =0.678).</p>
<p>De variabele <code>PISA_EigenInbreng</code> heeft wel een statistisch significant hoofdeffect (β = -0.05, p &lt; 0.05). Leerlingen die één eenheid hoger scoren op de mate waarin ze vinden eigen inbreng te mogen hebben in de les scoren 0.05 eenheden lager op technische geletterdheid. In de populatie verwachten we ook een effect gegeven de p-waarde die kleiner is dan 0.05. Onze hypothese met betrekking tot verschil in het effect van <code>PISA_EigenInbreng</code> tussen eerste- en tweedejaars dienen we te verwerpen. Het is niet zo dat leerlingen in het tweede jaar meer baat hebben bij het hebben van eigen inbreng in de les. Het interactie-effect van deze lesstijl met het jaar is niet significant (β = -0.007, p = 0.579). Anders gesteld: leerlingen uit het eerste of tweede jaar hebben dezelfde mate van eigen inbreng nodig in de les om technisch geletterder te worden.</p>
</section>
<section id="oefening-2" class="level2">
<h2 class="anchored" data-anchor-id="oefening-2">Oefening 2</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><i class="bi bi-journal-richtext"></i> Oefening 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>En hoe zit dat met de andere leerkrachtstijlen (<code>PISA_Experimenteren</code>; <code>PISA_Orientatie</code>)? Hebben die hetzelfde effect voor eerste en tweedejaars?</p>
<p>Gebruik opnieuw de dummyvariabele (<code>Tweedejaars</code>) om deze hypotheses te toetsen. Toets elk van die hypotheses in een afzonderlijk model.</p>
</div>
</div>
<p>We gaan eerst de twee nieuwe modellen schatten, ééntje met daarin <code>PISA_Experimenteren</code> als voorspeller en ééntje met <code>PISA_Orientatie</code> als voorspeller.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>M_Experimenteren <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  TAC.na <span class="sc">~</span> PISA_Experimenteren <span class="sc">+</span> Tweedejaars <span class="sc">+</span> PISA_Experimenteren <span class="sc">*</span> Tweedejaars,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> Techniek</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>M_Orientatie <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  TAC.na <span class="sc">~</span> PISA_Orientatie <span class="sc">+</span> Tweedejaars <span class="sc">+</span> PISA_Orientatie <span class="sc">*</span> Tweedejaars,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> Techniek</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We bekijken de output voor beide modellen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Experimenteren)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TAC.na ~ PISA_Experimenteren + Tweedejaars + PISA_Experimenteren * 
    Tweedejaars, data = Techniek)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.59012 -0.16213  0.00697  0.18210  0.41744 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      0.582276   0.029566  19.694   &lt;2e-16 ***
PISA_Experimenteren              0.001171   0.012381   0.095    0.925    
Tweedejaars                      0.028006   0.038866   0.721    0.471    
PISA_Experimenteren:Tweedejaars -0.011252   0.016513  -0.681    0.496    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2088 on 1675 degrees of freedom
  (688 observations deleted due to missingness)
Multiple R-squared:  0.000561,  Adjusted R-squared:  -0.001229 
F-statistic: 0.3134 on 3 and 1675 DF,  p-value: 0.8157</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M_Orientatie)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TAC.na ~ PISA_Orientatie + Tweedejaars + PISA_Orientatie * 
    Tweedejaars, data = Techniek)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.60970 -0.16449  0.00952  0.17363  0.42555 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  0.544560   0.028204  19.308   &lt;2e-16 ***
PISA_Orientatie              0.016128   0.010834   1.489    0.137    
Tweedejaars                 -0.005354   0.035844  -0.149    0.881    
PISA_Orientatie:Tweedejaars  0.005019   0.014177   0.354    0.723    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2083 on 1675 degrees of freedom
  (688 observations deleted due to missingness)
Multiple R-squared:  0.004543,  Adjusted R-squared:  0.002761 
F-statistic: 2.548 on 3 and 1675 DF,  p-value: 0.05431</code></pre>
</div>
</div>
<p>Wat beide andere lesstijlen betreft, blijkt dat de verklaarde variantie in technische geletterdheid (<code>TAC.na</code>) telkens verwaarloosbaar is (R-kwadraat Experimenteren= -0.0012, R-kwadraat Orientatie= 0.0028) en bovendien niet statistisch significant (p Experimenteren= 0.816, p Orientatie= 0.054). De onafhankelijke variabelen hebben dus geen effect op technische geletterdheid in de populatie. Bovendien is voor beide modellen zowel <code>Tweedejaars</code> (β Experimenteren = -0.007, p = 0.471; β Orientatie= 0.016, p = 0.137 ) als de interactie tussen <code>Tweedejaars</code> en lesstijl (β Experimenteren<em>Tweedejaars = -0.011, p = 0.496; β Orientatie</em>Tweedejaars= 0.005, p = 0.723) niet statistisch significant. In de populatie vinden we deze effecten dus niet terug.</p>
</section>
<section id="oefening-3" class="level2">
<h2 class="anchored" data-anchor-id="oefening-3">Oefening 3</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><i class="bi bi-journal-richtext"></i> Oefening 3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tijdens een vorig contactmoment gingen we al na in welke mate de interesse van leerlingen in het project (<code>Projectinteressant.z</code>) en de mate van interesse in techniek voor het project (<code>Interest.voor.z</code>) een invloed hebben op de interesse na het project (<code>Interest.na.z</code>).</p>
<p>Op basis van een uitgebreide literatuurstudie vermoeden we echter dat de interesse in techniek na het project niet voor alle studierichtingen hetzelfde is.</p>
<ol type="a">
<li><p>Ga deze hypothese na. Zet de variabele <code>Richting5cat</code> eerst om in de nodige dummyvariabelen. Hanteer vervolgens de studierichting “Technisch” als referentiecategorie in je analyses. Maak ook de nodige gestandaardiseerde variabelen aan.</p></li>
<li><p>Interpreteer vervolgens ook de andere parameterschattingen.</p></li>
</ol>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>We starten met het aanmaken van de nodige dummy-variabelen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Om te weten welke code van <code>Richting5cat</code> hoort bij welke studierichting grijp je best terug naar het codeboek.</p>
<p>In de onderstaande code maken we de dummy-variabelen aan. Soms voeren we nog een extra controle uit via het <code>table()</code> commando. Dat doen we hier niet. We zijn overtuigd dat we het goed deden 😀!</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Technisch <span class="ot">&lt;-</span> (Techniek<span class="sc">$</span>Richting5cat<span class="sc">==</span><span class="st">'1'</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Kunst     <span class="ot">&lt;-</span> (Techniek<span class="sc">$</span>Richting5cat<span class="sc">==</span><span class="st">'2'</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Latijn    <span class="ot">&lt;-</span> (Techniek<span class="sc">$</span>Richting5cat<span class="sc">==</span><span class="st">'3'</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>ModWet    <span class="ot">&lt;-</span> (Techniek<span class="sc">$</span>Richting5cat<span class="sc">==</span><span class="st">'4'</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Handel    <span class="ot">&lt;-</span> (Techniek<span class="sc">$</span>Richting5cat<span class="sc">==</span><span class="st">'5'</span>)<span class="sc">*</span><span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Daarnaast moeten we enkele variabelen standaardiseren.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Projectinteressant.z <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Projectinteressant)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Interest.voor.z      <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Interest.voor)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>Techniek<span class="sc">$</span>Interest.na.z        <span class="ot">&lt;-</span> <span class="fu">scale</span>(Techniek<span class="sc">$</span>Interest.na)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nu zijn we klaar om het gevraagde model te schatten en de output op te vragen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Model3a<span class="ot">&lt;-</span><span class="fu">lm</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  Interest.na.z <span class="sc">~</span> Projectinteressant.z <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    Interest.voor.z <span class="sc">+</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    Kunst <span class="sc">+</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    Latijn <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    ModWet <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    Handel,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>Techniek</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">summary</span>(Model3a)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interest.na.z ~ Projectinteressant.z + Interest.voor.z + 
    Kunst + Latijn + ModWet + Handel, data = Techniek)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9210 -0.4538  0.0149  0.4781  2.7577 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           0.28057    0.05886   4.767 1.99e-06 ***
Projectinteressant.z  0.18773    0.01643  11.423  &lt; 2e-16 ***
Interest.voor.z       0.56743    0.01706  33.259  &lt; 2e-16 ***
Kunst                -0.02814    0.13274  -0.212    0.832    
Latijn               -0.33973    0.06588  -5.157 2.73e-07 ***
ModWet               -0.31074    0.06355  -4.890 1.08e-06 ***
Handel               -0.30135    0.07370  -4.089 4.49e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7497 on 2236 degrees of freedom
  (124 observations deleted due to missingness)
Multiple R-squared:  0.4403,    Adjusted R-squared:  0.4388 
F-statistic: 293.2 on 6 and 2236 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>De hypothese klopt! Uit de analyses blijkt dat leerlingen die gemiddeld scoren op <code>Projectinteressant.z</code> en <code>Interest.voor.z</code> maar les volgen in de studierichtingen Latijn (β = -0.34, p &lt; 0.001), Moderne Wetenschappen (β = -0.311, p &lt; 0.001) of Handel (β = -0.301, p &lt; 0.001) significant lager scoren op <code>Interest.na.z</code> in vergelijking met leerlingen uit een technische richting. Het verschil in score op <code>Interest.na.z</code> tussen leerlingen uit Kunst en leerlingen uit een technische richting is niet significant (β = -0.028, p = 0.832).</p>
<ol start="2" type="a">
<li></li>
</ol>
<p>Een leerling uit een technische richting die gemiddeld scoort op ‘Projectinteressant.z’ en op ‘Interest.voor.z’ behaalt een score van 0.281 SD boven het gemiddelde (β 0 = 0.281, p &lt; 0.001). De kans dat het intercept in de populatie 0 bedraagt, is zeer klein (p &lt; 0.001). We gaan er dus vanuit dat dit ook voor de populatie geldt. Als we het effect van <code>Projectinteressant.z</code> op <code>Interest.na.z</code> vergelijken met dat van <code>Interest.voor.z</code> op <code>Interest.na.z</code>, dan blijkt dat het effect van de laatste variabele groter is. We mogen beide effecten vergelijken, omdat het in beide gevallen om gestandaardiseerde variabelen gaat.</p>
<p><code>Interest.voor.z</code> heeft een positief effect op <code>Interst.na.z</code> (β = 0.567, p &lt; 0.001). Voor elke SD die een leerling hoger scoort op <code>Interest.voor.z</code> stijgt diens score op <code>Interest.na.z</code> met 0.567 SD, ongeacht de studierichting waarin de leerling les volgt en diens score op <code>Project.interessant.z</code>. (Ook de toename in <code>Interest.na.z</code> mogen we in SD’s interpreteren aangezien ook deze variabele is gestandaardiseerd.) Aangezien de p-waarde kleiner is dan 0.05 verwachten we dit effect ook in de populatie terug te vinden. Hetzelfde geldt voor het effect van <code>Projectinteressant.z</code>. Eén SD hoger score op deze variabele leidt tot een toename van 0.188 SD op <code>Interest.na.z</code> (β = 0.188, p &lt; 0.001), ongeacht de studierichting waarin een leerling les volgt en zijn score op <code>Interest.voor.z</code>.</p>
<p>Ten slotte blijkt dat dit model 43.9% van de variantie in <code>Interest.na.z</code> verklaart (adj. R-kwadraat = 0.439) De F-toets leert dat we dit ook in de populatie mogen verwachten (F(6,2236) = 293.2, p &lt; 0.001). Dus ook de in populatie verklaren de onafhankelijke variabelen ene deel van de verschillen in interesse in techniek na het project.</p>
</section>
<section id="oefening-4" class="level2">
<h2 class="anchored" data-anchor-id="oefening-4">Oefening 4</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span><i class="bi bi-journal-richtext"></i> Oefening 4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ten slotte verwachten we dat het effect van <code>Interest.voor.z</code> op interesse in techniek mogelijk anders is voor leerlingen uit de studierichting “Technisch”.</p>
<ol type="a">
<li><p>Ga ook deze hypothese na. Rapporteer je bevindingen a.d.h.v. de output van je analyses.</p></li>
<li><p>Bereken de scores van volgende leerlingen in de steekproef en in de populatie:</p></li>
</ol>
<ul>
<li><p>een leerling die 0 scoort op alle onafhankelijke variabelen</p></li>
<li><p>een leerling uit een technische richting die 1SD hoger scoort op <code>Interest.voor.z</code> en 2 SD hoger scoort op <code>Projectinteressant.z</code></p></li>
</ul>
</div>
</div>
<ol type="a">
<li></li>
</ol>
<p>Om deze onderzoeksvraag op een efficiënte wijze te vertalen in een model is het handiger om een andere referentiecategorie te nemen voor studierichting dan <code>Technisch</code>. In de code hieronder kiezen we ervoor om een andere grotere groep leerlingen te hanteren als refentiecategorie: de leerlingen uit Moderne Wetenschappen. Dit zie je in de code omdat de dummy variabele <code>ModWet</code>niet is opgenomen in het model. De vraag naar het interactie-effect vertalen we in het model door de term <code>(Interest.voor.z * Technisch)</code> op te nemen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  Interest.na.z <span class="sc">~</span> Projectinteressant.z <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    Interest.voor.z <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    Technisch <span class="sc">+</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    Latijn <span class="sc">+</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    Kunst <span class="sc">+</span> </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    Handel <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    (Interest.voor.z <span class="sc">*</span> Technisch),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>Techniek</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Interest.na.z ~ Projectinteressant.z + Interest.voor.z + 
    Technisch + Latijn + Kunst + Handel + (Interest.voor.z * 
    Technisch), data = Techniek)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9124 -0.4541  0.0083  0.4787  2.7545 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               -0.030234   0.023577  -1.282  0.19985    
Projectinteressant.z       0.187985   0.016437  11.437  &lt; 2e-16 ***
Interest.voor.z            0.563815   0.017519  32.183  &lt; 2e-16 ***
Technisch                  0.253368   0.089634   2.827  0.00475 ** 
Latijn                    -0.029504   0.036677  -0.804  0.42124    
Kunst                      0.282396   0.120925   2.335  0.01962 *  
Handel                     0.008868   0.049540   0.179  0.85794    
Interest.voor.z:Technisch  0.066976   0.073794   0.908  0.36418    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7497 on 2235 degrees of freedom
  (124 observations deleted due to missingness)
Multiple R-squared:  0.4405,    Adjusted R-squared:  0.4388 
F-statistic: 251.4 on 7 and 2235 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>De vooropgestelde hypothese klopt niet! Uit de analyse blijkt dat het interactie-effect tussen <code>Interest.voor.z</code> en een technische studierichting volgen (<code>Technisch</code>) niet statistisch significant is (β = 0.067, p = 0.364). Het effect van <code>Interest.voor.z</code> op <code>Interest.na.z</code> is in de populatie dus niet anders voor leerlingen uit een technische studierichting.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Als dit wel statistisch significant zou zijn, dan zou dat betekenen dat voor leerlingen uit een technische studierichting het effect van <code>Interest.voor.z</code> op <code>Interest.na.z</code> groter zou zijn. 1 SD hoger scoren op <code>Interest.voor.z</code> leidt dan voor een leerling uit een technische studierichting tot een toename van 0.631 (= 0.564 + 0.067) SD op <code>Interest.na.z</code>.</p>
</div>
</div>
<ol start="2" type="a">
<li></li>
</ol>
<p><em>“Een leerling die 0 scoort op alle onafhankelijke variabelen”</em></p>
<p>… is een leerling die gemiddeld scoort op alle onafhankelijke kwantitatieve variabelen en die tot de referentiecategorie behoort (Moderne Wetenschappen). Onze beste inschatting is dat deze leerling zowel in de steekproef een score op <code>Interest.na.z</code> van -0.03 (= het intercept!) behaalt. Voor de populatie verwachten we dat zo’n leerling een score 0 behaalt (het intercept is immers niet statistisch significant).</p>
<p><em>“Een leerling uit een technische richting die 1 SD hoger scoort op <code>Interest.voor.z</code> en 2 SD hoger scoort op <code>Projectinteressant.z</code>”</em></p>
<p>Vooraleer we de berekeningen doen, schrijven we de regressievergelijking opnieuw op.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
    \text{Interest.na.Z}  = &amp; \beta_{0} + \beta_{1} \cdot \text{Projectinteressant.z} + \beta_{2} \cdot \text{Interest.voor.z} + \\
                            &amp; \beta_{3} \cdot \text{Technisch} + \beta_{4} \cdot \text{Latijn} + \beta_{5} \cdot \text{Kunst} + \beta_{6} \cdot \text{Handel} +\\
                            &amp; \beta_{7} \cdot (\text{Technisch} * \text{Interest.voor.z})
  \end{aligned}
\end{equation}\]</span></p>
<p>Voorspelde scores <strong>voor de steekproef</strong>:</p>
<p>Om de scores te berekenen voor de steekproef vullen we alle parameters in uit de output.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
    \text{Interest.na.Z} = &amp; \textcolor{green}{-0.03} + \textcolor{green}{0.188} \cdot \text{Projectinteressant.z} + \textcolor{green}{0.564} \cdot \text{Interest.voor.z} + \\
                            &amp; \textcolor{green}{0.253} \cdot \text{Technisch} + \textcolor{green}{-0.030} \cdot \text{Latijn} + \textcolor{green}{0.282} \cdot \text{Kunst} + \textcolor{green}{0.009} \cdot \text{Handel} +\\
                            &amp; \textcolor{green}{0.067} \cdot (\text{Technisch} * \text{Interest.voor.z})
  \end{aligned}
\end{equation}\]</span></p>
<p>Nu we de parameters hebben ingevuld, kunnen we ook de waarden voor de variabelen invullen die de betrokken leerling behaalt.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
    \text{Interest.na.Z}  = &amp; -0.03 + 0.188 \cdot \textcolor{red}{2} + 0.564 \cdot \textcolor{red}{1} + \\
                            &amp; 0.253 \cdot \textcolor{red}{1} + -0.030 \cdot \textcolor{red}{0} + 0.282 \cdot \textcolor{red}{0} + 0.009 \cdot \textcolor{red}{0} +\\
                            &amp; 0.067 \cdot (\textcolor{red}{1} * \textcolor{red}{1}) \textcolor{blue}{= 1.23}
  \end{aligned}
\end{equation}\]</span></p>
<p>Voorspelde scores <strong>voor de populatie</strong>:</p>
<p>Om de scores te berekenen voor de populatie vullen we enkel de statistisch significante parameters uit de output in onze vergelijking in. Parameters die niet statistisch significant zijn vervangen we door de waarde 0.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
    \text{Interest.na.Z} = &amp; \textcolor{green}{0} + \textcolor{green}{0.188} \cdot \text{Projectinteressant.z} + \textcolor{green}{0.564} \cdot \text{Interest.voor.z} + \\
                            &amp; \textcolor{green}{0.253} \cdot \text{Technisch} + \textcolor{green}{0} \cdot \text{Latijn} + \textcolor{green}{0.282} \cdot \text{Kunst} + \textcolor{green}{0} \cdot \text{Handel} +\\
                            &amp; \textcolor{green}{0} \cdot (\text{Technisch} * \text{Interest.voor.z})
  \end{aligned}
\end{equation}\]</span></p>
<p>Vervolgens kunnen we de waarden invullen die de bewuste leerling behaalde op elk van de variabelen in ons model.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
    \text{Interest.na.Z}  = &amp; 0 + 0.188 \cdot \textcolor{red}{2} + 0.564 \cdot \textcolor{red}{1} + \\
                            &amp; 0.253 \cdot \textcolor{red}{1} + 0 \cdot \textcolor{red}{0} + 0.282 \cdot \textcolor{red}{0} + 0 \cdot \textcolor{red}{0} +\\
                            &amp; 0 \cdot (\textcolor{red}{1} * \textcolor{red}{1}) \textcolor{blue}{= 1.193}
  \end{aligned}
\end{equation}\]</span></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© CC-By Universiteit Antwerpen, 2024</p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Wij maken gebruik van cookies om de surfervaring te verbeteren en om de website te optimaliseren. IP-adressen worden niet bewaard.</a></div></div>
    <div class="nav-footer-right">
<p>Gemaakt met veel ❤ en <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>